name: Node.js CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install typescript
      if: (matrix['os'] == 'macos-latest')
      run: npm install typescript -g
      shell: bash
    - name: Install semistandard
      run: npm install semistandard -g
    - run: npm install
    - run: npm test
      env:
        CI: true
        ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
